## 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.



In [36]:
import numpy as np

In [37]:
v = np.linspace(1, 10, num=10, dtype=int)
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


##2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.



In [38]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


##3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [39]:
m = np.random.randint(1, 10, (5, 5))
print(m)

[[7 4 9 7 7]
 [5 7 5 6 4]
 [5 8 8 6 1]
 [1 5 6 9 6]
 [3 8 1 9 7]]


##4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [40]:
m = np.random.random((4, 4))
print(m)

[[0.46202636 0.31890742 0.4903039  0.09540581]
 [0.80802542 0.03709019 0.428959   0.59806266]
 [0.63889661 0.66129113 0.21363254 0.28054233]
 [0.00395866 0.92187848 0.91637006 0.18343758]]


##5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [41]:
m1 = np.random.randint(1, 10, (5,))
m2 = np.random.randint(1, 10, (5,))
print(m1, m2)

[5 2 1 1 7] [2 8 1 5 5]


In [42]:
m_sum = m1 + m2
m_sub = m1 - m2
m_mult = m1 * m2
print(m_sum)
print(m_sub)
print(m_mult)


[ 7 10  2  6 12]
[ 3 -6  0 -4  2]
[10 16  1  5 35]


##6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [43]:
v1 = np.random.randint(1, 10, (7,))
v2 = np.random.randint(1, 10, (7,))
print(v1, v2)

[2 2 7 5 6 8 9] [8 7 6 9 7 7 3]


In [44]:
scalar_mult = np.dot(v1, v2)
print(scalar_mult)

242


##7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [45]:
m1 = np.random.randint(1, 10, (2, 2))
m2 = np.random.randint(1, 10, (2, 3))

print(m1, m2, sep='\n\n')

[[8 1]
 [8 5]]

[[7 6 3]
 [8 1 7]]


In [46]:
mult_m = np.dot(m1, m2)
print(mult_m)

[[64 49 31]
 [96 53 59]]


##8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [47]:
m = np.random.randint(1, 10, (3, 3))
print(m)

[[7 9 6]
 [4 8 6]
 [7 2 7]]


In [48]:
m_transp = np.transpose(m)
print(m_transp)

[[7 4 7]
 [9 8 2]
 [6 6 7]]


##9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.



In [49]:
m = np.random.random((4, 4))
print(m)

[[0.42588567 0.5859333  0.65648134 0.3286707 ]
 [0.40740802 0.18172575 0.97179904 0.03446314]
 [0.19867705 0.03419831 0.21248347 0.0269445 ]
 [0.38873278 0.41304896 0.74592211 0.07537606]]


In [50]:
m_transp = np.transpose(m)
print(m_transp)

[[0.42588567 0.40740802 0.19867705 0.38873278]
 [0.5859333  0.18172575 0.03419831 0.41304896]
 [0.65648134 0.97179904 0.21248347 0.74592211]
 [0.3286707  0.03446314 0.0269445  0.07537606]]


##10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [51]:
m = np.random.randint(1, 10, (3, 4))
v = np.random.randint(1, 10, (4,))

print(m, v, sep='\n\n')

[[4 5 8 1]
 [8 5 9 5]
 [8 9 2 8]]

[1 7 1 7]


##11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [52]:
m = np.random.random((2, 3))
v = np.random.random((3,))

print(m, v, sep='\n\n')

[[0.00281742 0.64489804 0.99853025]
 [0.71282154 0.75365702 0.03949225]]

[0.59107492 0.0685689  0.19880445]


In [53]:
mult_m = np.dot(m, v)

print(mult_m)

[0.24439752 0.4808596 ]


##12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [54]:
m1 = np.random.randint(1, 10, (2, 2))
m2 = np.random.randint(1, 10, (2, 2))

print(m1, m2, sep='\n\n')

[[9 8]
 [4 6]]

[[9 9]
 [8 7]]


In [55]:
mult_m = m1 * m2

print(mult_m)

[[81 72]
 [32 42]]


##13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [56]:
m1 = np.random.randint(1, 10, (2, 2))
m2 = np.random.randint(1, 10, (2, 2))

print(m1, m2, sep='\n\n')

[[2 7]
 [2 6]]

[[2 6]
 [5 4]]


In [57]:
mult_m = np.dot(m1, m2)

print(mult_m)

[[39 40]
 [34 36]]


##14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [58]:
m = np.random.randint(1, 100, (5, 5))

print(m)

[[53 16 41 61 48]
 [36 35 95 78 13]
 [ 7  4 87 11 67]
 [98 39 96 87 49]
 [56 58 73 94 35]]


In [59]:
sum = np.sum(m)

print(sum)

1337


##15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [60]:
m1 = np.random.randint(1, 10, (4, 4))
m2 = np.random.randint(1, 10, (4, 4))

print(m1, m2, sep='\n\n')

[[9 2 2 7]
 [5 6 7 5]
 [6 7 2 6]
 [7 7 2 9]]

[[4 7 7 4]
 [4 9 4 8]
 [1 4 9 7]
 [6 8 4 5]]


In [61]:
sub = np.subtract(m1, m2)

print(sub)

[[ 5 -5 -5  3]
 [ 1 -3  3 -3]
 [ 5  3 -7 -1]
 [ 1 -1 -2  4]]


##16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [62]:
m = np.random.random((3, 3))

print(m)

[[0.80242524 0.39890257 0.01546266]
 [0.80014947 0.39855539 0.71483706]
 [0.15346301 0.07935538 0.58144723]]


In [63]:
sum_row = np.sum(m, axis=1)
vertical_v = sum_row.reshape(-1, 1)

print(sum_row, vertical_v, sep='\n\n')

[1.21679047 1.91354192 0.81426562]

[[1.21679047]
 [1.91354192]
 [0.81426562]]


##17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [64]:
m = np.random.randint(1, 10, (3, 4))

print(m)

[[5 3 1 7]
 [4 1 1 3]
 [9 1 3 7]]


In [65]:
square_m = np.square(m)

print(square_m)

[[25  9  1 49]
 [16  1  1  9]
 [81  1  9 49]]


##18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [66]:
v = np.random.randint(1, 50, (4,))

print(v)

[27 42 44 11]


In [67]:
square_root_v = np.sqrt(v)

print(square_root_v)

[5.19615242 6.4807407  6.63324958 3.31662479]
